### ISSUE TITLE
Which protocol did you use to implement the send module?

### ISSUE THREAD

**Issue by fernandojunior** [yushuhuang/webcam#1]
I wanna send a stream captured from webcam using openCv via RTSP protocol.
Are you using a specific protocol to implement the send module?

**Comment by yushuhuang** [comment]
Thank you for your interest in my project. Actually, it was just a simple
demo of OpenCV, and I think the only protocol I used to send jpg was UDP.

**Comment by fernandojunior** [comment]
Ok, thank you!
